package br.ecq.Bounties.service;

public enum BountyResult {
    SUCCESS,
    NO_PERMISSION,
    CANNOT_SELF,
    BYPASS,
    INSUFFICIENT_FUNDS,
    INVALID_AMOUNT,
    TOO_LOW,
    TOO_HIGH,
    PLAYER_NOT_FOUND,
    ON_COOLDOWN,
    MAX_ACTIVE_PLACED,
    MAX_AMOUNT_PLACED,
    NOT_IN_COMBAT,
    BOUNTY_NOT_FOUND,
    NOT_CONTRIBUTOR
}
